### ISSUE TITLE
无线驱动的丢包率严重

### ISSUE THREAD

**Issue by hsmliu** [OpenIntelWireless/itlwm#367] opened 2020-10-29 07:18 UTC
AirportItlwm-Big_Sur在bigsur系统的丢包率严重，我测试ping www.baidu.com -c 10000  大概20次左右丢包一次

**Comment by williambj1** [comment] 2020-10-29 07:29
Unable to reproduce this issue on my laptop. Make sure you are not uploading extensively, which may exceed the driver's current compacity and cause issues. Closing as the issue format is invalid.

**Closed by williambj1** 2020-10-29 07:29 UTC
