### ISSUE TITLE
[FEATURE REQUEST] Support for Location Services?

### ISSUE THREAD

**Issue by NotARobot6969** [OpenIntelWireless/itlwm#222] opened 2020-07-31 20:44 UTC
I get it's emulating ethernet currently for the internet support, but, y'know, it'd be cool for Siri to know where I live.

**Comment by ErrorErrorError** [comment] 2020-07-31 20:56
As far as I've read, it needs Apple80211, which is a closed source. I don't think it's possible at this state, but maybe in the future once, however don't quote me on that.

**Comment by williambj1** [comment] 2020-08-01 00:17
Duplicate of #182

**Comment by williambj1** [comment] 2020-08-01 00:17
Duplicate of #194

**Comment by williambj1** [comment] 2020-08-01 00:18
Duplicate of #40

**Closed by williambj1** 2020-08-01 00:17 UTC
