### ISSUE TITLE
will it be supported EDUROAM for University Campus

### ISSUE THREAD

**Issue by mehmetyukcell** [OpenIntelWireless/itlwm#230] opened 2020-08-03 05:59 UTC
I am an PhD student in the university. will it be supported for eduroam internet connection?

**Comment by ErrorErrorError** [comment] 2020-08-03 06:03
As of now there are still things that need to be implemented before you will be able to connect to networks that require Username and password

**Comment by mehmetyukcell** [comment] 2020-08-03 07:04
> As of now there are still things that need to be implemented before you will be able to connect to networks that require Username and password 

what are these things? I have username and password. i will try to connect next week with Eduroam in the campus.

**Comment by ErrorErrorError** [comment] 2020-08-03 07:09
https://github.com/OpenIntelWireless/HeliPort/issues/4

**Comment by mehmetyukcell** [comment] 2020-08-03 08:29
> https://github.com/OpenIntelWireless/HeliPort/issues/4
> 

Thanks for your interest, Sincerely

**Comment by williambj1** [comment] 2020-08-15 05:44
Duplicate of #101

**Closed by williambj1** 2020-08-15 05:44 UTC
