### ISSUE TITLE
Handoff and shared clipboard partially work

### ISSUE THREAD

**Issue by enPause96** [OpenIntelWireless/itlwm#337] opened 2020-10-07 19:17 UTC
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: AirportItlwm 1.2.0
- WiFi Card Model: Intel Wireless N 7260
- Product ID: 0x08B1
- macOS Version: Big Sur 11.0 beta 8

**Description**

Handoff and shared clopboard work only in one direction. Handoff icon doesn't show on dock when i use Safari, Message, Mail on my iPhone but when i use them on my PC i can see them on iPhone. also i can access to the clipboard of my PC on my iPhone but can't access of clipboard of my iPhone from PC
i tried resetting network preferences and log out then relog in on both my devices but didn't work
**Bug Report Archive**

[AirportItlwm.log](https://github.com/OpenIntelWireless/itlwm/files/5342415/AirportItlwm.log)
real time airport log https://pastebin.pl/view/d577d059
**Kext Download Source**

from official OpenIntelWireless github

![Capture d’écran 2020-10-07 à 17 39 00](https://user-images.githubusercontent.com/65020150/95362988-c6fdca00-08c6-11eb-8362-2d9cd5dc0c00.png)
![Capture d’écran 2020-10-07 à 17 39 44](https://user-images.githubusercontent.com/65020150/95363002-c9f8ba80-08c6-11eb-9654-f4ed6428e481.png)

**Comment by williambj1** [comment] 2020-10-08 02:53
Still sounds like a userspace issue to me. The logs didn't contain useful information for debugging continuity. Maybe you can contact people that own the same card as yours to help us identify whether it's a card-specific or a userspace issue.

**Comment by williambj1** [comment] 2020-10-08 02:54
Duplicate of #292

**Closed by williambj1** 2020-10-08 02:54 UTC
