### ISSUE TITLE
Ventura: Slow wifi connection, delayed menu bar icons

### ISSUE THREAD

**Issue by bin1117** [OpenIntelWireless/itlwm#832] opened 2022-12-04 12:04 UTC
**Have You Read Our Docs**
                   Yes

**Are You Reporting A Bug**
                  yes 

**Environment**

- Kext Version: 2.20-alpha(2484f03)
- WiFi Card Model: Intel AX200
- PCI Product ID: 0x8086, 0x84
- macOS Version: Ventura 13.0.1

**Description**
After each restart, the menu bar icons, such as: time, wifi, and Bluetooth icons will not appear until 20 seconds after booting up (the problem of icon delay will not appear if you turn off AirportItlwm.kext), and the Wi-Fi connection speed will increase. There is a 10-20 second delay, these issues appear on Ventura, everything works fine in Monterey

**Comment by williambj1** [comment] 2022-12-04 13:12
Duplicate of #823

**Closed by williambj1** 2022-12-04 13:12 UTC
