### ISSUE TITLE
airportltlwm在macOS15上不工作，itlwm+heliport正常

### ISSUE THREAD

**Issue by Eternity070628** [OpenIntelWireless/itlwm#995] opened 2024-07-01 03:26 UTC
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 2.3.0
- WiFi Card Model: 
- PCI Product ID: 
- macOS Version: 15

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment] 2024-07-02 08:12
Duplicate of #983

**Closed as not planned by williambj1** 2024-07-02 08:12 UTC
Labels: duplicate
