### ISSUE TITLE
Internet speed is very slow in Intel 9560 Wi-Fi card. 

### ISSUE THREAD

**Issue by md-siam** [OpenIntelWireless/itlwm#202] opened 2020-07-23 03:40 UTC
Hi,

First of all, thank you for your hard works. 
Internet speed is very slow in Intel 9560 Wi-Fi card in 5GHz. I checked the "Link Speed" and it is showing only 100Mbps whereas it should be around 860Mbps. The "Link Speed" in 2.4GHz is also only 100Mbps.

**Comment by williambj1** [comment] 2020-07-23 03:50
duplicate of #198

**Closed by williambj1** 2020-07-23 03:50 UTC
