### ISSUE TITLE
Handoff + Hotspot = NO

### ISSUE THREAD

**Issue by chris1111** [OpenIntelWireless/itlwm#244] opened 2020-08-11 00:26 UTC
Do you please add support for Handoff + Hotspot 
Not work here macOS Big Sur Beta 4 with ➤ [PCE-AC55BT-B1](https://www.asus.com/ca-en/Networking/PCE-AC55BT-B1/)

Thanks for your support
![Capture d’écran, le 2020-08-10 à 20 23 51](https://user-images.githubusercontent.com/6248794/89843836-d58a6800-db47-11ea-814b-0f071600afab.png)

**Comment by ErrorErrorError** [comment] 2020-08-11 01:27
Duplicate of https://github.com/OpenIntelWireless/itlwm/issues/188.

**Closed** 2020-08-11 02:13 UTC
