### ISSUE TITLE
8265 performance - Catalina

### ISSUE THREAD

**Issue by sylwesterr** [OpenIntelWireless/itlwm#223] opened 2020-07-31 22:01 UTC
Hi,
I have noticed that the performance of my 8265 card is around half of normal... I have 100Mbps internet connection. When performing Speedtest.net on my built in Intel 8265 I am reaching max around 50Mbps download and 10Mbps upload. Then testing the same on USB Edimax card that has dedicated drivers for Catalina, I am reaching the correct speeds of around 100Mbps download and 20Mbps upload.... Especially interesting is the upload test ... can you advise reliable link speed verification method?
I am attaching itlwm.log collected using:
log show --last boot | grep itlwm >~/Desktop/itlwm.log
let me know if I can provide any further debug details or perform any tests.
[itlwm.log](https://github.com/OpenIntelWireless/itlwm/files/5009195/itlwm.log)

**Comment by ErrorErrorError** [comment] 2020-07-31 22:05
Duplicate of https://github.com/OpenIntelWireless/itlwm/issues/180.

**Closed** 2020-08-01 00:16 UTC
