### ISSUE TITLE
Wise Tiger AX210NGW WIFI 6E on Big Sur

### ISSUE THREAD

**Issue by iii0s** [OpenIntelWireless/itlwm#694] opened 2021-10-03 08:19 UTC
**Have You Read Our Docs**

yes

**Are You Reporting A Bug**

no - (Enhancement)

**Environment**

    Kext Version: 2.1.0 alpha (Big Sur)
    WiFi Card Model: Wise Tiger AX210NGW WIFI 6E
    PCI Product ID: Vendor 8086, Device 2725
    macOS Version: Big Sur 11.6

**Description**

I have downloaded the itlwm 2.1.0 alpha release and tried it on my Asus Rog Hackintosh with the following WIFI card.
https://www.amazon.de/gp/product/B08NSSJNV1/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

The thing is that it does not work if I boot into Big Sur directly, however, when I boot into Windows 10 and restart choosing Big Sur, the card works fine except for the bluetooth mouse. I am actually writing this now using my Big Sur and connected to WIFI.

One thing I have noticed though is that I cannot connect to hidden networks!

I am not using the Airport version, but the itlwm v2.1.0-alpha.

Is there a simple way to fix this?

**Bug Report Archive**

**Kext Download Source**

https://github.com/OpenIntelWireless/itlwm/releases/download/v2.1.0-alpha/itlwm-v2.1.0-DEBUG-alpha-2e06227.zip

**Comment by williambj1** [comment] 2021-10-03 09:48
Duplicate of #693

**Closed by williambj1** 2021-10-03 09:48 UTC
