### ISSUE TITLE
WiFi doesn't work with ax210 on Big Sur

### ISSUE THREAD

**Issue by wqhqq1** [OpenIntelWireless/itlwm#624] opened 2021-06-11 14:35 UTC
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: 2.0.0
- WiFi Card Model: ax210
- Product ID: 
- macOS Version: 11.3

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment] 2021-06-11 14:40
Duplicate of #446

**Closed by williambj1** 2021-06-11 14:40 UTC
