### ISSUE TITLE
Connecting to a network that requires username and password

### ISSUE THREAD

**Issue by 666ares** [OpenIntelWireless/itlwm#186] opened 2020-07-14 14:49 UTC
How to connect to a network that requires username and password to connect to it?

**Comment by techies23** [comment] 2020-07-15 11:31
**This does not seem to be an issue you are asking in this issue thread.** In order for a developer or anyone to understand you need to clarify what you did and how you did to reach certain situation.

Anyway, if it helps - I am very new to Hackintosh however, i successfully implemented this awesome tool by the developer and it works pretty darn well i must say. Really a big thanks to the developer here !

I have a Lenovo y7000P 144hz series which had a RTL8822BE card which does not seem to work. So, switched it to Intel 9520 family since i could not find the Broadcom card on my side of the world. 

To enable it, just added **itlwm.kext** inside **EFI/Clover/kexts/other** and Installed "**HeliPort**" App, Restart and it seemed to do the trick. Although, i need to restart a few times to get the Wifi working sometimes but who cares i got it working for now.

Just ran a **sudo kextload -i /** thinking this would reset any cache ( please anyone let me know what exactly this does if you want )

This is all using Clover Configurator.

**Comment by williambj1** [comment] 2020-07-15 11:38
Enterprise-level encryption is currently not supported, stay tuned.

@techies23 This issue is actually valid, thank you for your interest in this project.

**Comment by williambj1** [comment] 2020-07-15 13:04
Duplicate of #161

**Closed by williambj1** 2020-07-15 13:04 UTC
