### ISSUE TITLE
AC7260 Can't Connect to Network And Can't Refresh Wifi AP List

### ISSUE THREAD

**Issue by coolderin** [OpenIntelWireless/itlwm#705] opened 2021-10-30 07:28 UTC
**Have You Read Our Docs**
Yes
**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.0 and 2.1.0 alpha
- WiFi Card Model: AC7260
- PCI Product ID: (08B1)
- macOS Version: Big Sur 11.6 20G165

**Description**
I can't connect to my 5G and 2.4G wireless access points. It (Wifi) can't refresh network list but if i turn off&on my wifi it can refresh network list once.

**Bug Report Archive**
Wifi Diagnostics: https://drive.google.com/drive/folders/1Czf-VAPb3bVn-Y_YHqKVE95J93PVhiXf?usp=sharing
Log: [Log_2021-10-30_09-56-51.log](https://github.com/OpenIntelWireless/itlwm/files/7446005/Log_2021-10-30_09-56-51.log)

**Kext Download Source**
https://drive.google.com/file/d/1N09OzzkgUaVoAqNKX8TvJ5o8uHxL-33Y/view?usp=sharing (2.0 and 2.1 alpha)
I use these kexts.

**Comment by DNCTrung** [comment] 2021-11-07 07:42
Same to me with Wireless 3160 after updated. I have to get back 1.3.0. It's working.

**Comment by zxystd** [comment] 2021-11-07 14:20
> Same to me with Wireless 3160 after updated. I have to get back 1.3.0. It's working.

Have you tried v2.1.0-alpha?

**Comment by zxystd** [comment] 2021-11-07 14:22
@coolderin Maybe you can try change to another ssid? Or can your try if it can connect with cellphone hotspot?

**Comment by coolderin** [comment] 2021-11-07 14:51
I tried to connect my cellphone hotspot (2.4G)  and changed my ssid (5G) (eg. "abcd efg" to "abcdefg") it didn't work. I tried on version 2.0.

**Comment by zxystd** [comment] 2021-11-07 15:24
@coolderin what about itlwm.kext? if error still exist, please collect the log again. should be noticed that ac7260 have an connection issue on version 2.0.0, fixed in v2.1.0-alpha.

**Comment by coolderin** [comment] 2021-11-07 16:03
[itlwm=heliport.log](https://github.com/OpenIntelWireless/itlwm/files/7492606/itlwm.heliport.log)
Here is itlwm.kext log ver 2.1.0-alpha. Both of kexts (Airport and Heliport) 2.4Ghz network was connected once.
And System Information>WiFi section my Wifi device ID was 4470 but my device id is 0B81.

**Comment by zxystd** [comment] 2021-11-09 01:21
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/16227538/140843531-f7954557-ea99-434e-824a-d28d4f97eefa.png">

why putting itlwm.kext and AirportItlwm.kext together?

> And System Information>WiFi section my Wifi device ID was 4470 but my device id is 0B81.

0x4470 is subdevice id, not device id. I have ac7260 with id 0x0B82 and it works fine.

**Comment by coolderin** [comment] 2021-11-09 15:53
[last-itlwm-notairport.log](https://github.com/OpenIntelWireless/itlwm/files/7506146/last-itlwm-notairport.log)

Here is the "no airport" log. But itlwm disabled the airportitlwm. Is there any problem?

**Comment by zxystd** [comment] 2021-11-09 16:12
@coolderin what's the meaning of 'itlwm disabled the airportitlwm'? I can see the card is init/connect succeed, but sometimes it acquires device fail, seems that something is racing the ownership of the card.

**Comment by coolderin** [comment] 2021-11-09 16:55
I mean when I use airportitlwm and itlwm at same times, itlwm block the airportitlwm. Now I try only itlwm with Heliport, I can't connect to my APs.

**Comment by williambj1** [comment] 2021-11-10 00:11
What makes you think they can coexist with each other? Does your imaginary "blocking" mechanism work in real life? Closed since this is an obvious user mistake, read the docs and use the products as intended.

**Closed by williambj1** 2021-11-10 00:11 UTC

**Comment by coolderin** [comment] 2021-11-10 19:41
No sir, I didn't make mistake,
In first log (https://github.com/OpenIntelWireless/itlwm/files/7446005/Log_2021-10-30_09-56-51.log) I didn't use itlwm, I used airportitlwm.
When developer said did you try itlwm with heliport, i tried itlwm with airportitlwm (itlwm already block airportitlwm and itlwm be active), then https://github.com/OpenIntelWireless/itlwm/files/7492606/itlwm.heliport.log i sent log, dev said try with only itlwm then i sent only (https://github.com/OpenIntelWireless/itlwm/files/7506146/last-itlwm-notairport.log) log.
So, I didn't make mistake (maybe i did in 2nd log.)
Please don't close this topic.

**Comment by jssunhaimin** [comment] 2021-11-16 15:55
我的是Intel 7260， Macos 10.15.7的环境， 使用的是2.0驱动 连WIFI 2.4G正常。

连接WIFI 5G没有数据，WIFI图标上有个感叹号！ 目前日常使用的是WIFI2.4G
