### ISSUE TITLE
Compatibility with 6235

### ISSUE THREAD

**Issue by isa-pp** [OpenIntelWireless/itlwm#271] opened 2020-08-25 11:25 UTC
Hi, I have a thinkpad t440p using a Intel 6235, product ID 0x08FF, the itlwm kext recognizes it and tries to connect during boot but it won't. Bluetooth works perfectly, but I want to ask if there's any plans to support this device

**Comment by williambj1** [comment] 2020-08-25 13:20
Duplicate of #112

**Closed by williambj1** 2020-08-25 13:20 UTC
