### ISSUE TITLE
存在间歇性断网 Intermittent network disconnection exists

### ISSUE THREAD

**Issue by xbctmri** [OpenIntelWireless/itlwm#348] opened 2020-10-13 12:16 UTC
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: itlwm 1.10 Stable 
- WiFi Card Model: AC-9560
- Product ID: Unknown
- macOS Version: 10.13.6 17G14033

**Description**

本人将itlwm搭配Heliport使用，在使用过程中发现偶尔出现无法连接WIFI的情况。有时就算连接WIFI成功了之后不到几秒钟就断开了。最严重的情况下Heliport没有任何相应。
I used ITLWM with Heliport, and found that WIFI could not be connected occasionally during the use. Sometimes even if the WIFI connection is successful, it will be disconnected within a few seconds. In the worst case, Heliport doesn't have any response.

**Bug Report Archive**

[bugreport_24601.zip](https://github.com/OpenIntelWireless/itlwm/files/5371164/bugreport_24601.zip)
(The breakdown described in the issue just occurred again, so I urgently upload two latest reports)
[bugreport_47975.zip](https://github.com/OpenIntelWireless/itlwm/files/5372273/bugreport_47975.zip)
[bugreport_13265.zip](https://github.com/OpenIntelWireless/itlwm/files/5372275/bugreport_13265.zip)
(Edited at 14 October: Today I found that this driver is no longer available. I tried to connect to all available WIFI, but it failed. This is the latest report.)
[bugreport_49668.zip](https://github.com/OpenIntelWireless/itlwm/files/5375229/bugreport_49668.zip)

**Kext Download Source**

Downloaded from "releases" page of this project

**Comment by williambj1** [comment] 2020-10-13 12:26
CC @zxystd

**Comment by zxystd** [comment] 2020-10-14 14:38
关闭路由器上5g跟2.4g ssid合并功能即可。

**Comment by xbctmri** [comment] 2020-10-16 02:44
> 关闭路由器上5g跟2.4g ssid合并功能即可。

好吧，这个路由器是公司的，我没有管理权。

**Comment by bsed** [comment] 2020-10-16 04:00
`关闭路由器上5g跟2.4g ssid合并功能即可`。 即使按照上述方法配置后，如果连接的桥接的路由器wifi 也会出现上述问题，我用的是2个xiaomi 路由器

**Comment by williambj1** [comment] 2020-10-16 09:20
Duplicate of #333

**Closed by williambj1** 2020-10-16 09:20 UTC
Labels: question
