### ISSUE TITLE
[Feature request] Make this kext act as a native WiFi device

### ISSUE THREAD

**Issue by GGorAA** [OpenIntelWireless/itlwm#261] opened 2020-08-16 11:40 UTC
Hello,

I really love what you have created. This is the only kext that allowed me to use my Intel WiFi card! But there is one thing that I don't like: this kext acts as a Ethernet device instead of Ethernet device. And, to make it act like a Wifi, you need HeliPort installed, which is inconvenient.

So here is feature request, and also a question: Can you make it act like a WiFi device, and if you will, when you will do it?

**Comment by williambj1** [comment] 2020-08-16 12:19
Duplicate of #233

**Closed by williambj1** 2020-08-16 12:19 UTC
