### ISSUE TITLE
Bluetooth is unstable while Wi-Fi is enabled

### ISSUE THREAD

**Issue by vivzero** [OpenIntelWireless/itlwm#542] opened 2021-03-05 18:17 UTC
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: AirportItlwm v1,2,0
- WiFi Card Model: Intel Dual Band Wireless-AC 7260
- Product ID: 0x4070
- macOS Version: 10,15,7 (19H524)

**Description**

Either Wi-Fi or Bluetooth is works well, but not both. 
When turn Wi-Fi on, Bluetooth is almost gone.

- AirPods doesn't work. it works only when turn off Wi-fi.
- Magic Mouse works. But stability get worse sharply with increasing distances from laptop.

**Bug Report Archive**

[AirItlDebug_2021-03-06_01-59-07.zip](https://github.com/OpenIntelWireless/itlwm/files/6092032/AirItlDebug_2021-03-06_01-59-07.zip)

**Kext Download Source**
 
[GitHub](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0)

**Comment by williambj1** [comment] 2021-03-06 01:15
Duplicate of #482

**Closed by williambj1** 2021-03-06 01:15 UTC
