### ISSUE TITLE
No Networks Found (but wifi hardware / bluetooth detected.

### ISSUE THREAD

**Issue by tlefko** [OpenIntelWireless/itlwm#361] opened 2020-10-20 04:52 UTC
**I can't open the issue template that's why this is likely not formatted correctly 

Hey guys, I tried to install this using clover forcing IO802 to load from the System, as well as tried placing in the clover folder itself along with airportitwlm. itlwm works well, but when trying to use the airportitwlm it is unable to find any networks. I'm not really sure what I'm doing wrong, below I've attached a zip (with overkill) all the system information you may need to help diagnose the problem. I'm not really familiar with OpenCore and struggled deeply to get it setup so that's why I'm on clover. I currently have the Matebook X pro 2018 model. Regardless, I'll upload the files (sorry if format isn't good)

if I didn't;t give the right info or made a mistake please just let me know and I'll resolve rather than just close the issue, thank you :=

[Archive.zip](https://github.com/OpenIntelWireless/itlwm/files/5406336/Archive.zip)
<img width="616" alt="Screen Shot 2020-10-20 at 12 52 16 AM" src="https://user-images.githubusercontent.com/42879340/96541709-8e6ad280-126e-11eb-9ee7-044d532eda75.png">
<img width="965" alt="Screen Shot 2020-10-20 at 12 52 35 AM" src="https://user-images.githubusercontent.com/42879340/96541710-90349600-126e-11eb-8ecd-68bbeb151579.png">

EDIT: Just tried with opencore, forcing Io802 to load and still same issue. Scanning finds no result

**Comment by mehmetyukcell** [comment] 2020-10-20 05:20
Delete IO80211family, again tried. Also, what is your wifi model?

**Comment by tlefko** [comment] 2020-10-20 05:48
> Delete IO80211family, again tried. Also, what is your wifi model?

Deleted it, retried but no luck. Same result with it removed. The model is the Intel ac 8265 @mehmetyukcell

**Comment by williambj1** [comment] 2020-10-20 06:15
@tlefko Force load IO80211Family, and ask about the details in Reddit or Insanlymac.

Sorry but I must close this issue since this is not a bug report of our product.

**Comment by mehmetyukcell** [comment] 2020-10-20 06:16
İf You using opencore, should be show the kext with opencore configurator in the kernel kexts

**Closed by williambj1** 2020-10-20 06:15 UTC

**Comment by tlefko** [comment] 2020-10-20 06:17
> @tlefko Force load IO80211Family, and ask about the details in Reddit or Insanelymac.
> 
> Sorry but I must close this issue since this is not a bug report of our product.

hey, thanks for that I appreciate you going out of your way for the suggestion. I'll take that advice. Awesome work guys
