### ISSUE TITLE
Wireless adapter does not turn on after sleep 

### ISSUE THREAD

**Issue by startergo** [OpenIntelWireless/itlwm#647] opened 2021-07-17 13:21 UTC
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: Itlwm 1.3.0
- WiFi Card Model: Centrino Advanced-N 6205 [Taylor Peak] 
- PCI Product ID: DID 0082 SVID 8086  SDID 1301
- macOS Version: 10.13.6

**Description**
Wireless Interface would not turn on after sleep. Need to reboot the system to get it working.

**Bug Report Archive**
[bugreport_39195.zip](https://github.com/OpenIntelWireless/itlwm/files/6834748/bugreport_39195.zip)

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.3.0

**Comment by zxystd** [comment] 2021-07-17 14:15
@startergo The problem is fixed in alpha-v2.0.0, can you try it?

**Comment by startergo** [comment] 2021-07-17 14:27
Works now great!. I was trying to build the latest commit from source, but I got some errors in Xcode:
![image](https://user-images.githubusercontent.com/7897244/126040173-4ec4d5c5-1e1b-41ae-a6c8-c0cae048b2df.png)

**Closed** 2021-07-17 17:43 UTC
