### ISSUE TITLE
If you meet low connect speed in WPA3-supported network with AirportItlwm

### ISSUE THREAD

**Issue by ZhiShengYuan** [OpenIntelWireless/itlwm#712] opened 2021-11-13 06:59 UTC
as this issue `https://github.com/OpenIntelWireless/itlwm/issues/701` 
disable WPA3 or use itlwm.kext instead.

**Comment by williambj1** [comment] 2021-11-13 07:34
Duplicate of #701

**Closed by williambj1** 2021-11-13 07:34 UTC
