### ISSUE TITLE
Intel (R) Centrino(R) Ultimate-N 6300 AGN

### ISSUE THREAD

**Issue by tardar** [OpenIntelWireless/itlwm#385] opened 2020-11-08 13:33 UTC
Hey guys,

would you plant add this much older card to the compatibility list of the kext?

Thanks really alot :)

Have a nice sunday
Tardar

**Comment by williambj1** [comment] 2020-11-08 13:38
Duplicate of #112

**Closed by williambj1** 2020-11-08 13:38 UTC
