### ISSUE TITLE
Boot time on Big Sur really long

### ISSUE THREAD

**Issue by Yot360** [OpenIntelWireless/itlwm#402] opened 2020-11-17 21:31 UTC
Hey, I updated to Big Sur and now my boot times went from 20s to 5mins (on ssd). I watched the boot process with verbose on, and like 2/3 of the boot process is itlwm, I think it’s really slowing down my boot speed but I need it for WiFi.

**Comment by VoltaVX** [comment] 2020-11-17 22:04
It's normal for ITLWM to spam your verbose mode a bit, but it doesn't prevent the system from booting up. I think you might be missing [the Catalina AHCI Kext](https://github.com/dortania/OpenCore-Install-Guide/blob/master/extra-files/CtlnaAHCIPort.kext.zip) which got removed in Big Sur. Add that kext to OpenCore, and your computer should be able to boot up as fast as before.

**Comment by williambj1** [comment] 2020-11-17 22:54
Duplicate of #353

**Closed by williambj1** 2020-11-17 22:54 UTC

**Comment by Yot360** [comment] 2020-11-18 12:26
> It's normal for ITLWM to spam your verbose mode a bit, but it doesn't prevent the system from booting up. I think you might be missing [the Catalina AHCI Kext](https://github.com/dortania/OpenCore-Install-Guide/blob/master/extra-files/CtlnaAHCIPort.kext.zip) which got removed in Big Sur. Add that kext to OpenCore, and your computer should be able to boot up as fast as before.

Thanks gonna try
